name: Code Review Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.xml'
      - '**.java'

jobs:
  review:
    name: Automated Code Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run PR code analysis
        uses: gitleaks/gitleaks-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      
      - name: Analyze code quality changes
        uses: reviewdog/action-suggester@v1.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: code-review-assistant
          level: warning
      
      - name: Android best practices check
        uses: mobiledevops/android-checkstyle-githubaction@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
