name: Documentation Generation

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.java'
      - '**.md'
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Generate Dokka documentation
        run: ./gradlew dokkaHtml
      
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: app/build/dokka/html/
      
      # Optionally deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/dokka/html/
          destination_dir: api-docs
