name: Android Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  code-quality:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          java-version: '17'
          distribution: 'microsoft'          
        
      - name: Run Android Lint
        # Use the existing baseline file to only fail on new issues
        run: |
          echo "Running lint with baseline from repository"
          ./gradlew lintDebug --no-configuration-cache
        # abortOnError=true in build.gradle.kts will make the build fail if lint finds new issues beyond the baseline
      
      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-configuration-cache
        
      - name: Run Detekt
        run: ./gradlew detekt --no-configuration-cache
          
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-reports
          path: |
            app/build/reports/lint-results*.html
            app/build/reports/lint-results*.xml
            build/reports/ktlint/
            app/build/reports/ktlint/
            build/reports/detekt/
            app/build/reports/detekt/
