name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: PR title check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (based on Conventional Commits)
          types:
            - feat
            - fix
            - docs
            - style
            - refactor
            - perf
            - test
            - build
            - ci
            - chore
            - revert
          # Validate that PRs have a valid JIRA ticket number (e.g., PROJ-123)
          # requireJiraIssue: true
          # jiraIssueRegex: '[A-Z]+-[0-9]+'
      
      - name: Check PR size
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*\.(kt|kts|xml|java|gradle)$
          MAX_CHANGES: 500 # Warn if PR has more than 500 lines changed
