name: Android Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests & Generate Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'ms'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      
      - name: Generate Code Coverage Report
        if: success()
        run: ./gradlew jacocoTestReport
      
      # Commented out as CodeCov is not set up yet
      # - name: Upload Coverage to Codecov
      #   if: success()
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
      #     fail_ci_if_error: true
      #     verbose: true
          
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests/
            app/build/reports/jacoco/
